// lib/service-data.ts
import {
  Zap,
  Shield,
  PiggyBank,
  HandCoins,
  Files,
  Handshake,
  Landmark,
  BarChart,
  Settings,
  Users,
  Scale,
  BookCopy,
  TrendingUp,
  User,
  UserPlus,
  Building,
  Briefcase,
  Gem,
  HeartHandshake,
} from "lucide-react";

export const serviceData = {
  // =================================================================================
  // 1. Sole Proprietorship
  // =================================================================================
  proprietorship: {
    title: "Sole Proprietorship Registration",
    breadcrumb: ["Home", "Registrations", "Proprietorship"],
    overview:
      "A proprietorship is a business owned and managed by a single individual, making it the most basic and widely chosen business structure in India. The owner has complete control over all operations and decisions. In this structure, the business and the owner are considered the same legal entity. This means the owner keeps all profits but is also personally responsible for all business debts and losses, a concept known as unlimited liability.",
    advantages: [
      {
        icon: Zap,
        title: "Easy to Set Up",
        text: "The registration process involves minimal documentation and legal formalities.",
      },
      {
        icon: Shield,
        title: "Complete Control",
        text: "The owner has full authority over all business decisions and operations.",
      },
      {
        icon: HandCoins,
        title: "Direct Profits",
        text: "All profits generated by the business belong solely to the owner.",
      },
      {
        icon: Files,
        title: "Minimal Compliance",
        text: "Fewer regulatory obligations compared to other company structures.",
      },
    ],
    disadvantages: [
      {
        icon: Zap,
        title: "Unlimited Liability",
        text: "The owner's personal assets are at risk to cover business debts.",
      },
      {
        icon: Landmark,
        title: "Difficulty Raising Capital",
        text: "Cannot sell shares and may find it hard to secure loans.",
      },
      {
        icon: BarChart,
        title: "Limited Lifespan",
        text: "The business is tied to the owner and may cease if the owner retires or dies.",
      },
    ],
    eligibility: [
      {
        title: "General Requirements",
        items: [
          "Must be a resident citizen of India.",
          "Must be at least 18 years old.",
          "A unique business name must be chosen.",
        ],
      },
      {
        title: "Business Activity",
        items: [
          "The business activity must be legal and not prohibited by law.",
          "Necessary permits must be obtained for regulated industries.",
        ],
      },
      {
        title: "Financial & Other",
        items: [
          "A business bank account must be opened.",
          "A physical or home-based business address is required.",
        ],
      },
    ],
    documents: [
      {
        tabTitle: "Proprietor Documents",
        content: {
          title: "Proprietor's Identity & Address Proof",
          items: [
            "Aadhaar Card",
            "PAN Card (Mandatory)",
            "Passport-size Photographs",
            "Bank Account Details",
          ],
        },
      },
      {
        tabTitle: "Business Address Proof",
        content: {
          title: "Proof of Business Location",
          items: [
            "Utility Bill (for owned or rented property)",
            "Rent Agreement (if rented)",
            "No-Objection Certificate (NOC) from Landlord",
          ],
        },
      },
      {
        tabTitle: "Key Registrations",
        content: {
          title: "Registrations & Licenses",
          items: [
            "GST Registration (if applicable)",
            "MSME/Udyam Registration",
            "Shop and Establishment Act License",
          ],
        },
      },
    ],
    registrationProcess: [
      {
        step: 1,
        title: "Choose a Business Name",
        description: "Select a unique name for your proprietorship.",
      },
      {
        step: 2,
        title: "Select a Business Location",
        description:
          "Decide on your business address, which can be commercial or residential.",
      },
      {
        step: 3,
        title: "Open a Business Bank Account",
        description:
          "Open a current account in the name of the proprietorship.",
      },
      {
        step: 4,
        title: "Obtain Basic Registrations",
        description:
          "Apply for necessary registrations like the Shop and Establishment Act License and Udyam Registration.",
      },
      {
        step: 5,
        title: "Apply for GST Registration",
        description:
          "If your business turnover exceeds the GST threshold, you must obtain GST registration.",
      },
    ],
    fees: [
      {
        component: "GST Registration",
        fees: "Free",
        remarks: "Mandatory if turnover exceeds ₹40 lakh for goods.",
      },
      {
        component: "MSME (Udyam) Registration",
        fees: "Free",
        remarks: "Optional, but beneficial for government schemes.",
      },
      {
        component: "Shop & Establishment License",
        fees: "₹1,000 – ₹5,000",
        remarks: "Fees vary by state and business size.",
      },
    ],
    faqs: [
      {
        q: "What is unlimited liability?",
        a: "Unlimited liability means the owner is personally responsible for all business debts. If the business cannot pay its debts, the owner's personal assets can be used to cover them.",
      },
      {
        q: "Is GST registration mandatory for a proprietorship?",
        a: "GST registration is mandatory only if your annual turnover exceeds the specified threshold (e.g., ₹40 lakhs for goods) or if you sell goods across states.",
      },
    ],
  },

  // =================================================================================
  // 2. Partnership Firm
  // =================================================================================
  partnership: {
    title: "Partnership Firm Registration",
    breadcrumb: ["Home", "Registrations", "Partnership"],
    overview:
      "A Partnership Firm is a business structure where two or more individuals agree to carry on a business and share the profits. It is governed by the Indian Partnership Act, 1932. While registration is optional, a registered partnership firm enjoys several legal benefits and protections.",
    advantages: [
      {
        icon: Handshake,
        title: "Easy Formation",
        text: "Partnership deeds are relatively simple to create and the business can be set up quickly.",
      },
      {
        icon: Users,
        title: "Larger Resources",
        text: "Partners can pool their financial resources and skills for greater business potential.",
      },
      {
        icon: Settings,
        title: "Flexibility",
        text: "Operations and decision-making are flexible and can be adapted quickly by the partners.",
      },
    ],
    disadvantages: [
      {
        icon: Zap,
        title: "Unlimited Liability",
        text: "All partners are personally liable for the firm's debts, jointly and severally.",
      },
      {
        icon: Handshake,
        title: "Potential for Conflicts",
        text: "Disagreements between partners can arise, affecting the business.",
      },
      {
        icon: BarChart,
        title: "Instability",
        text: "The firm can be dissolved upon the death, retirement, or insolvency of a partner.",
      },
    ],
    documents: [
      {
        tabTitle: "Firm Documents",
        content: {
          title: "Partnership Firm Documents",
          items: [
            "Partnership Deed (duly notarized)",
            "PAN Card of the Firm",
            "Address Proof of the Firm (Utility bill, Rent Agreement)",
          ],
        },
      },
      {
        tabTitle: "Partner Documents",
        content: {
          title: "Documents for All Partners",
          items: [
            "PAN Card of all partners",
            "Address Proof of all partners (Aadhaar, Voter ID, Passport)",
            "Passport-size photographs of all partners",
          ],
        },
      },
    ],
    registrationProcess: [
      {
        step: 1,
        title: "Drafting the Partnership Deed",
        description:
          "A legal expert drafts the partnership deed, which outlines the rights, duties, profit sharing ratios, and other rules among partners.",
      },
      {
        step: 2,
        title: "Notarization of the Deed",
        description:
          "The partnership deed must be signed by all partners and notarized on a non-judicial stamp paper.",
      },
      {
        step: 3,
        title: "Applying for Firm's PAN",
        description:
          "An application for the PAN (Permanent Account Number) of the partnership firm is made.",
      },
      {
        step: 4,
        title: "Registration with Registrar of Firms",
        description:
          "An application is filed with the Registrar of Firms of the respective state, along with the deed and required documents.",
      },
    ],
    faqs: [
      {
        q: "Is it mandatory to register a partnership firm?",
        a: "No, registration is optional under the Indian Partnership Act, 1932. However, an unregistered firm cannot sue third parties and faces other legal disabilities, making registration highly advisable.",
      },
      {
        q: "What is a Partnership Deed?",
        a: "A Partnership Deed is a legal agreement between the partners that outlines the terms and conditions of the partnership, including profit/loss sharing, roles, capital contribution, and dispute resolution.",
      },
    ],
  },

  // =================================================================================
  // 3. Limited Liability Partnership (LLP)
  // =================================================================================
  llp: {
    title: "LLP Registration",
    breadcrumb: ["Home", "Registrations", "LLP"],
    overview:
      "A Limited Liability Partnership (LLP) is a corporate business form that offers the benefits of limited liability to its partners while allowing them the flexibility of organizing their internal structure as a traditional partnership. It is a separate legal entity from its partners.",
    advantages: [
      {
        icon: Shield,
        title: "Limited Liability",
        text: "Partners' personal assets are protected from the business's debts.",
      },
      {
        icon: Landmark,
        title: "Separate Legal Entity",
        text: "An LLP can own property and enter into contracts in its own name.",
      },
      {
        icon: TrendingUp,
        title: "Perpetual Succession",
        text: "The LLP's existence is not affected by the entry or exit of partners.",
      },
      {
        icon: Scale,
        title: "Credibility",
        text: "An LLP is viewed as a more credible and organized business structure than a general partnership.",
      },
    ],
    disadvantages: [
      {
        icon: BookCopy,
        title: "Higher Compliance",
        text: "Requires mandatory annual filings with the MCA, like Form-8 and Form-11.",
      },
      {
        icon: PiggyBank,
        title: "Profit Distribution",
        text: "Profits must be distributed as per the LLP agreement.",
      },
      {
        icon: Handshake,
        title: "Complex to Form",
        text: "The formation process is more detailed and involves digital signatures and DINs.",
      },
    ],
    documents: [
      {
        tabTitle: "Partner Documents",
        content: {
          title: "Documents for Designated Partners",
          items: [
            "PAN Card of all partners",
            "Address Proof of partners (Aadhaar, Bank Statement, etc.)",
            "Passport-size photographs",
            "Digital Signature Certificate (DSC)",
          ],
        },
      },
      {
        tabTitle: "Registered Office Proof",
        content: {
          title: "LLP Office Address Proof",
          items: [
            "Utility Bill of the registered office premise",
            "No-Objection Certificate (NOC) from the property owner",
          ],
        },
      },
    ],
    registrationProcess: [
      {
        step: 1,
        title: "Obtain DSC and DIN",
        description:
          "All designated partners must obtain a Digital Signature Certificate (DSC) and a Director Identification Number (DIN).",
      },
      {
        step: 2,
        title: "Name Reservation (RUN-LLP)",
        description:
          "An application is filed with the MCA to reserve a unique name for the LLP.",
      },
      {
        step: 3,
        title: "Filing of FiLLiP Form",
        description:
          "The FiLLiP (Form for incorporation of Limited Liability Partnership) is filed, containing details of the LLP, partners, and registered office.",
      },
      {
        step: 4,
        title: "Drafting the LLP Agreement",
        description:
          "After incorporation approval, the LLP agreement is drafted and must be filed with the MCA in Form-3 within 30 days.",
      },
    ],
    faqs: [
      {
        q: "How many designated partners are required for an LLP?",
        a: "An LLP must have at least two designated partners, and at least one of them must be a resident of India.",
      },
      {
        q: "What is the difference between a partnership and an LLP?",
        a: "The primary difference is liability. In a partnership, partners have unlimited liability. In an LLP, partners have limited liability, meaning their personal assets are protected.",
      },
    ],
  },

  // =================================================================================
  // 4. One Person Company (OPC)
  // =================================================================================
  "one-person-company": {
    title: "One Person Company (OPC) Registration",
    breadcrumb: ["Home", "Registrations", "OPC"],
    overview:
      "A One Person Company (OPC) is a type of private limited company that can be formed with just one member and one director (who can be the same person). It provides the benefits of a corporate structure, such as limited liability, to a single entrepreneur.",
    advantages: [
      {
        icon: User,
        title: "Single Owner",
        text: "Allows a sole entrepreneur to run a business with a corporate identity.",
      },
      {
        icon: Shield,
        title: "Limited Liability",
        text: "The owner's personal assets are protected from business debts.",
      },
      {
        icon: TrendingUp,
        title: "Perpetual Succession",
        text: "The company continues to exist even after the death of the member, through a nominee.",
      },
    ],
    disadvantages: [
      {
        icon: Users,
        title: "Not for Every Business",
        text: "Not suitable for all business types, especially those requiring significant external funding.",
      },
      {
        icon: Files,
        title: "Compliance Burden",
        text: "Requires more compliance formalities than a proprietorship, including annual filings.",
      },
    ],
    documents: [
      {
        tabTitle: "Director & Nominee",
        content: {
          title: "Director and Nominee Documents",
          items: [
            "PAN Card of Director and Nominee",
            "Identity & Address Proof (Aadhaar, Voter ID)",
            "Photograph of Director and Nominee",
            "Consent of Nominee in Form INC-3",
          ],
        },
      },
      {
        tabTitle: "Registered Office",
        content: {
          title: "Registered Office Proof",
          items: [
            "Proof of office address (Utility Bill)",
            "No-Objection Certificate (NOC) from the owner",
          ],
        },
      },
    ],
    registrationProcess: [
      {
        step: 1,
        title: "Obtain DSC and DIN",
        description:
          "The sole director must obtain a Digital Signature Certificate (DSC) and a Director Identification Number (DIN).",
      },
      {
        step: 2,
        title: "Name Approval (SPICe+ Part A)",
        description:
          "Apply for the reservation of a unique name for the company.",
      },
      {
        step: 3,
        title: "Filing of SPICe+ Part B",
        description:
          "After name approval, file Part B of the SPICe+ form, which includes details about the company, director, and nominee.",
      },
      {
        step: 4,
        title: "Receive Certificate of Incorporation",
        description:
          "Once the MCA approves the forms, the Certificate of Incorporation is issued, along with the company's PAN and TAN.",
      },
    ],
    faqs: [
      {
        q: "Who can be a nominee in an OPC?",
        a: "The nominee must be an Indian citizen and resident who is not a minor. The same person cannot be a nominee for more than one OPC.",
      },
    ],
  },

  // =================================================================================
  // 5. Private Limited Company
  // =================================================================================
  "private-limited-company": {
    title: "Private Limited Company Registration",
    breadcrumb: ["Home", "Registrations", "Private Limited"],
    overview:
      "A Private Limited Company is a privately held business entity, governed by the Companies Act, 2013. It is the most popular corporate structure for businesses in India, offering limited liability, perpetual succession, and the ability to raise funds easily.",
    advantages: [
      {
        icon: Shield,
        title: "Limited Liability",
        text: "The liability of members is limited to their share contribution, protecting personal assets.",
      },
      {
        icon: Landmark,
        title: "Separate Legal Entity",
        text: "The company is a distinct legal entity, separate from its owners (shareholders).",
      },
      {
        icon: PiggyBank,
        title: "Easy to Raise Funds",
        text: "Can raise capital from venture capitalists, angel investors, and banks more easily than other structures.",
      },
      {
        icon: TrendingUp,
        title: "Perpetual Succession",
        text: "The company's existence is unaffected by the death or departure of its members.",
      },
    ],
    disadvantages: [
      {
        icon: BookCopy,
        title: "Strict Compliance",
        text: "Requires adherence to numerous regulations under the Companies Act, including board meetings and annual filings.",
      },
      {
        icon: Files,
        title: "Complex Formation",
        text: "The registration process is more complex and costly compared to proprietorships or partnerships.",
      },
    ],
    documents: [
      {
        tabTitle: "Directors & Shareholders",
        content: {
          title: "Documents for Directors and Shareholders",
          items: [
            "PAN Card",
            "Identity Proof (Aadhaar/Voter ID)",
            "Address Proof (Bank Statement)",
            "Photographs",
          ],
        },
      },
      {
        tabTitle: "Registered Office",
        content: {
          title: "Registered Office Proof",
          items: [
            "Utility Bill (Electricity/Phone Bill)",
            "Rent Agreement and NOC from the property owner if rented",
          ],
        },
      },
    ],
    registrationProcess: [
      {
        step: 1,
        title: "Obtain DSC and DIN for all Directors",
        description:
          "All proposed directors must have a Digital Signature Certificate (DSC) and Director Identification Number (DIN).",
      },
      {
        step: 2,
        title: "Reserve Company Name (SPICe+ Part A)",
        description:
          "File an application to reserve a unique name for the company with the MCA.",
      },
      {
        step: 3,
        title: "File Incorporation Forms (SPICe+ Part B)",
        description:
          "File the main e-form SPICe+ Part B, along with linked forms for MOA (Memorandum of Association) and AOA (Articles of Association).",
      },
      {
        step: 4,
        title: "Receive Incorporation Certificate",
        description:
          "Upon verification, the Registrar of Companies (ROC) issues the Certificate of Incorporation, making the company a legal entity.",
      },
    ],
    faqs: [
      {
        q: "What is the minimum requirement to start a Private Limited Company?",
        a: "You need a minimum of two directors and two shareholders (they can be the same people), and at least one director must be a resident of India.",
      },
    ],
  },

  // =================================================================================
  // 6. Nidhi Company
  // =================================================================================
  "nidhi-company": {
    title: "Nidhi Company Registration",
    breadcrumb: ["Home", "Registrations", "Nidhi Company"],
    overview:
      "A Nidhi Company is a type of Non-Banking Financial Company (NBFC) recognized under the Companies Act, 2013. Its core business is borrowing and lending money only among its members. It functions to cultivate the habit of thrift and savings among its members.",
    advantages: [
      {
        icon: PiggyBank,
        title: "Easy Access to Capital",
        text: "Can raise funds easily from its members without external intervention.",
      },
      {
        icon: Shield,
        title: "Limited Liability",
        text: "The liability of members is limited to the capital they have contributed.",
      },
      {
        icon: Files,
        title: "Simpler Regulations",
        text: "Exempt from many of the stringent provisions of the RBI Act that apply to other NBFCs.",
      },
    ],
    disadvantages: [
      {
        icon: Users,
        title: "Restricted Business",
        text: "Can only transact with its own members; cannot deal with the general public.",
      },
      {
        icon: Landmark,
        title: "High Capital & Member Requirement",
        text: "Must meet specific requirements for net owned funds and number of members within one year.",
      },
    ],
    documents: [
      {
        tabTitle: "Directors & Members",
        content: {
          title: "Documents for Directors and Members",
          items: [
            "PAN Card and Address Proof of all 7 initial members/directors",
            "Photographs",
          ],
        },
      },
      {
        tabTitle: "Registered Office",
        content: {
          title: "Registered Office Proof",
          items: [
            "Utility Bill and NOC from the landlord if the premises are rented.",
          ],
        },
      },
    ],
    registrationProcess: [
      {
        step: 1,
        title: "Obtain DSC and DIN",
        description: "A minimum of 3 directors must obtain their DSC and DIN.",
      },
      {
        step: 2,
        title: "Reserve Company Name",
        description:
          "Apply for a unique name for the Nidhi Company, which must end with 'Nidhi Limited'.",
      },
      {
        step: 3,
        title: "File Incorporation Documents",
        description:
          "File the SPICe+ form, MOA, and AOA with the MCA. The object of the company must be cultivating thrift and savings.",
      },
      {
        step: 4,
        title: "Receive Incorporation Certificate",
        description:
          "The ROC issues the Certificate of Incorporation upon successful verification.",
      },
    ],
    faqs: [
      {
        q: "What are the minimum requirements for Nidhi Company registration?",
        a: "A Nidhi Company must be a public company with a minimum paid-up equity share capital of ₹10 lakhs. It requires a minimum of 7 members and 3 directors.",
      },
    ],
  },

  // =================================================================================
  // 7. Section 8 Company (NGO)
  // =================================================================================
  "section-8-company": {
    title: "Section 8 Company (NGO) Registration",
    breadcrumb: ["Home", "Registrations", "Section 8 Company"],
    overview:
      "A Section 8 Company is a type of Non-Governmental Organization (NGO) registered for promoting commerce, art, science, sports, education, research, social welfare, religion, charity, or environmental protection. Its profits must be used to further these objects and not be distributed as dividends to its members.",
    advantages: [
      {
        icon: HeartHandshake,
        title: "Charitable Objects",
        text: "Operates for non-profit objectives, enhancing social welfare.",
      },
      {
        icon: Shield,
        title: "Separate Legal Entity",
        text: "Has its own legal identity, separate from its members, with perpetual succession.",
      },
      {
        icon: Gem,
        title: "Tax Exemptions",
        text: "Eligible for various tax exemptions under the Income Tax Act after obtaining 80G and 12A registrations.",
      },
      {
        icon: Scale,
        title: "High Credibility",
        text: "A Section 8 company is highly credible as it is licensed and regulated by the Central Government.",
      },
    ],
    disadvantages: [
      {
        icon: PiggyBank,
        title: "No Profit Distribution",
        text: "Profits cannot be distributed as dividends to members and must be reinvested into the company's objectives.",
      },
      {
        icon: BookCopy,
        title: "Strict Compliance",
        text: "Subject to stringent legal compliance under the Companies Act and other laws.",
      },
    ],
    documents: [
      {
        tabTitle: "Directors & Members",
        content: {
          title: "Director/Member Documents",
          items: [
            "PAN Card",
            "Identity and Address Proof (Aadhaar/Voter ID)",
            "Photographs",
          ],
        },
      },
      {
        tabTitle: "Registered Office",
        content: {
          title: "Registered Office Proof",
          items: ["Utility Bill and NOC from the property owner."],
        },
      },
    ],
    registrationProcess: [
      {
        step: 1,
        title: "Obtain DSC and DIN",
        description: "All proposed directors must obtain their DSC and DIN.",
      },
      {
        step: 2,
        title: "Name Reservation",
        description:
          "Apply for a unique name. The name must include words like Foundation, Forum, Association, etc.",
      },
      {
        step: 3,
        title: "File for License (Form INC-12)",
        description:
          "An application for a license is made to the Regional Director in Form INC-12.",
      },
      {
        step: 4,
        title: "File for Incorporation (SPICe+)",
        description:
          "After the license is granted, file the SPICe+ form for incorporation with the ROC.",
      },
    ],
    faqs: [
      {
        q: "Can a Section 8 Company make a profit?",
        a: "Yes, a Section 8 Company can generate profits. However, these profits must be used to promote the company's charitable objects and cannot be distributed to its members as dividends.",
      },
    ],
  },
};
