// lib/data/services/12a-registration.ts

import { ServiceData } from "@/lib/types";

export const a12aRegistrationData: ServiceData = {
  title: "12A Registration",
  breadcrumb: ["Home", "Registrations", "12A Registration"],
  overview:
    `The **12A registration** is a mandatory, one-time registration granted by the Income Tax Department in India to **Non-Profit Organizations (NPOs)**, which include trusts, societies, and Section 8 companies. Its primary purpose is to allow these organizations to claim an **exemption on their income** from taxation. Without this registration, the income generated by the NPO, even if used entirely for charitable or religious purposes, would be subject to standard income tax rates, significantly impacting their ability to serve their objectives.

This registration is a crucial first step for any NPO starting its operations. Once granted, it remains **valid indefinitely**, unless specifically cancelled by the Commissioner of Income Tax. It legally recognizes the organization as a charitable entity for tax purposes. To obtain the registration, the organization must submit an application in Form 10A (or Form 10AB for provisional registration) along with its foundational documents and financial statements to the Commissioner of Income Tax, who verifies its genuine nature and charitable objectives.

The most significant benefit of holding 12A registration is the **complete exemption of the NPO\'s income** used for charitable or religious purposes from income tax, as per Sections 11 and 12 of the Income Tax Act, 1961. This not only ensures that maximum funds are available for the organization\'s mission but also builds **credibility** for the NPO. Furthermore, having 12A registration is a prerequisite for obtaining **80G registration**, which allows donors to claim a deduction on their taxable income for contributions made to the NPO.`,
  advantages: [
    {
        icon: "CheckCircle",
        title: "of 12A Registration",
        text: "1.  **Income Tax Exemption:** This is the primary and most significant advantage. An NPO with 12A registration can claim full exemption from income tax on its surplus income, provided the income is utilized for its charitable or religious objectives. This allows the organization to dedicate more funds directly to its mission rather than paying taxes. 2.  **Enhanced Credibility and Trust:** 12A registration acts as an official recognition by the Income Tax Department that the organization is genuinely involved in charitable or religious activities. This significantly boosts the NPO\\'s credibility and builds trust among potential donors, beneficiaries, and the public. 3.  **Gateway to Funding and 80G:**",
        subPoints: [
            "**80G Registration:** It is a mandatory prerequisite for applying for 80G registration. With 80G, donors can claim a tax deduction on their contributions, which is a huge incentive for individuals and corporations to donate.",
            "**Access to Grants:** Many government grants, corporate social responsibility (CSR) funds, and international funding agencies often require the recipient organization to have valid 12A (and sometimes 80G) registration. 4.  **Accumulation of Income:** Registered organizations are permitted to accumulate up to 15% of their income without it being taxed. This flexibility allows NPOs to save for future projects or unforeseen expenses."
        ]
    }
],
  disadvantages: [
    {
        icon: "CheckCircle",
        title: "of 12A Registration",
        text: "1.  **Stringent Compliance and Reporting:** NPOs with 12A registration are subject to stricter compliance requirements. They must maintain meticulous books of accounts, get them audited (if applicable), and file their income tax returns (ITR-7) annually, detailing the application of funds. Non-compliance can lead to the cancellation of registration. 2.  **Strict \\\"Application of Income\\\" Rules:** To maintain the tax-exempt status, organizations generally must apply at least 85% of their income towards their charitable or religious objectives within the financial year. Failure to do so can result in the unapplied portion being taxed. 3.  **Renewal Burden (Every 5 Years):** Under the revised provisions (post-Finance Act, 2020), 12A registration is no longer a one-time lifetime registration. It is initially provisional for three years, and then requires **renewal every five years**. This introduces an administrative burden and recurring compliance costs for the NPO. 4.  **Restrictions on Business Income:** While some incidental business activities are allowed, if the income from such activities exceeds 20% of the total receipts of the organization, the entire income may become taxable. The primary objective must remain charitable. 5.  **Potential for Cancellation:** If an NPO is found to be engaged in non-charitable activities, or if there are violations of the Income Tax Act provisions, its 12A registration can be cancelled by the Commissioner of Income Tax, leading to the loss of all tax benefits."
    }
],
  eligibility: [
    {
        title: "Assuming you are referring to 12A Registration (under Section",
        items: [
            "12A/12AB of the Income Tax Act, 1961) for Non-Profit Organizations (NPOs) in India, here are the key eligibility criteria:    **Key Eligibility Criteria for 12A Registration**  The primary goal of the organization must align with the definition of \\\"Charitable or Religious Purpose\\\" under the Income Tax Act."
        ]
    },
    {
        title: "Legal Constitution of the Entity",
        items: [
            "**Charitable Trust:** Registered under the Indian Trusts Act or relevant state laws.",
            "**Society:** Registered under the Societies Registration Act, 1860, or a similar state-specific Act.",
            "**Section 8 Company:** A non-profit company registered under Section 8 of the Companies Act, 2013.",
            "**Religious Institution:** Established for religious purposes (must be a **Public Religious Trust**, not a Private/Family Trust)."
        ]
    },
    {
        title: "Charitable or Religious Objective",
        items: [
            "Relief of the Poor",
            "Education",
            "Medical Relief",
            "Preservation of the Environment (including watersheds, forests, and wildlife)",
            "Preservation of Monuments or places or objects of artistic or historic interest",
            "Advancement of any other object of general public utility"
        ]
    },
    {
        title: "Non-Profit Motive & Application of Income",
        items: [
            "**No Private Benefit:** The organization\\'s income, assets, and activities must be utilized solely for the charitable or religious objectives. No part of the income can be used, directly or indirectly, for the personal benefit of the founder, trustees, directors, or their relatives.",
            "**No Political Activity:** The organization should not be involved in any political activities or support any political party or candidate.",
            "**Business Activity Limit:** If the organization carries on any business, the income from such business must be entirely applied toward its charitable objects, and the receipts from this business should generally not exceed **20%** of the total receipts of the organization."
        ]
    },
    {
        title: "Compliance and Transparency",
        items: [
            "**Proper Books of Accounts:** The organization must maintain transparent, accurate, and prescribed **books of accounts** detailing all its receipts and expenditures.",
            "**Audit Requirement:** If the total income (before claiming exemptions) exceeds the basic exemption limit (currently \u20b9 2.5 Lakh), the organization\\'s accounts must be **audited** by a Chartered Accountant.",
            "**Filing of Returns:** The organization must file its Income Tax Return (ITR-7) annually on time."
        ]
    }
],
  documents: [
    {
        tabTitle: "Statutory & Foundation Documents",
        content: {
            title: "Statutory & Foundation Documents",
            items: [
                "**Instrument of Creation:** ",
                "**Trust:** Self-certified copy of the **Trust Deed** (with two copies).",
                "**Society:** Self-certified copy of the **Memorandum of Association (MOA)** and **Rules & Regulations/Bylaws**.",
                "**Section 8 Company:** Self-certified copy of the **Memorandum of Association (MOA)** and **Articles of Association (AOA)**. ",
                "**Registration Certificate:** Self-certified copy of the **Certificate of Registration** with the relevant authority (e.g., Registrar of Public Trusts, Registrar of Societies, or Registrar of Companies).",
                "**PAN Card:** Self-certified copy of the **PAN Card** of the Trust/Institution/NGO.",
                "**Object Modification (if any):** Self-certified copy of documents evidencing the adoption or modification of the objects of the organization (if applicable)."
            ]
        }
    },
    {
        tabTitle: "Financial & Activity Documents",
        content: {
            title: "Financial & Activity Documents",
            items: [
                "**Annual Accounts:** ",
                "For existing entities: Self-certified copies of the **Annual Accounts** (Balance Sheet, Income & Expenditure Account, and Audit Report) for the period not exceeding **3 financial years** immediately preceding the year of application (if the organization has been in existence for that long). *Note:* Accounts must be audited if the total income exceeds the basic exemption limit. ",
                "**Notes on Activities:** A detailed note on the **activities** of the trust or institution since its inception or during the preceding 3 years.",
                "**Business Income Details (if applicable):** If the organization\\'s income includes profits and gains from business, copies of the annual accounts and **audit report under Section 44AB** for the preceding 3 years are required."
            ]
        }
    },
    {
        tabTitle: "Key Personnel & Address Proof",
        content: {
            title: "Key Personnel & Address Proof",
            items: [
                "**KYC of Governing Body:** List of members of the Governing Body/Trustees/Directors, along with their details (Name, Father\\'s Name, Age, **PAN**, and **Aadhaar**).",
                "**Registered Office Address Proof:** Self-certified copy of utility bills (e.g., Electricity bill, Water bill, House Tax Receipt) for the registered office address.",
                "**NOC (No-Objection Certificate):** If the registered office is rented, a **No-Objection Certificate (NOC)** from the landlord."
            ]
        }
    },
    {
        tabTitle: "Prior Registration & Compliance (If Applicable)",
        content: {
            title: "Prior Registration & Compliance (If Applicable)",
            items: [
                "**Existing 12A/12AA Order:** Self-certified copy of the existing order granting registration under the former **Section 12A** or **12AA** (for re-registration applications).",
                "**FCRA Registration:** Self-certified copy of registration under the **Foreign Contribution (Regulation) Act, 2010** (if the applicant is registered under this Act).",
                "**Rejection Order (if any):** Self-certified copy of any previous order rejecting an application for registration under Section 12A or 12AA."
            ]
        }
    }
  ],
  registrationProcess: [
    {
      step: 1,
      title: "Log in to E-Filing Portal",
      description:
        "Log in to the official Income Tax Department's e-filing portal using the NGO's PAN credentials.",
    },
    {
      step: 2,
      title: "Navigate to Form 10A",
      description:
        "Go to 'e-File' > 'Income Tax Forms' > 'File Income Tax Forms' and select 'Form 10A - Application for registration'.",
    },
    {
      step: 3,
      title: "Fill the Application Form",
      description:
        "Complete the online Form 10A with accurate details about the NGO, its members, and its activities.",
    },
    {
      step: 4,
      title: "Attach Documents and Submit",
      description:
        "Upload scanned copies of all the required documents and submit the application using the Digital Signature Certificate (DSC) of the authorized person.",
    },
    {
      step: 5,
      title: "Verification and Approval",
      description:
        "The Income Tax department (Commissioner of Exemptions) will review the application. If satisfied, they will grant the 12A registration.",
    },
  ],
  fees: [
    {
      component: "Government Fee",
      fees: "Free",
      remarks:
        "There is no government fee for filing Form 10A or for obtaining 12A registration.",
    },
    {
      component: "Professional Fees",
      fees: "₹7,000 - ₹15,000",
      remarks:
        "For professional assistance with the application process, documentation, and follow-up with the tax department.",
    },
  ],
  faqs: [
    {
      q: "What is the difference between 12A and 80G registration?",
      a: "12A registration exempts the NGO's income from tax. 80G registration allows donors who give money to the NGO to claim a tax deduction on their own income. 12A is for the NGO's benefit, while 80G is for the donor's benefit.",
    },
    {
      q: "Is 12A registration a one-time process?",
      a: "Yes, under the new rules, NGOs get a provisional registration for 3 years, after which they need to apply for a final registration which is then valid for 5 years and needs to be renewed. Previously granted lifetime registrations also need to be re-validated.",
    },
    {
      q: "What happens if an NGO does not have 12A registration?",
      a: "Without 12A registration, the NGO's entire surplus income is treated as regular taxable income and is taxed at the applicable slab rates. It also cannot apply for government funding or an 80G certificate.",
    },
  ],
};
