// lib/data/services/proprietorship.ts

import { ServiceData } from "@/lib/types";

export const proprietorshipData: ServiceData = {
  title: "Sole Proprietorship Registration",
  breadcrumb: ["Home", "Registrations", "Proprietorship"],
  overview:
    "A proprietorship is a business owned and managed by a single individual, making it the most basic and widely chosen business structure in India. The owner has complete control over all operations and decisions. In this structure, the business and the owner are considered the same legal entity. This means the owner keeps all profits but is also personally responsible for all business debts and losses, a concept known as unlimited liability.",
  advantages: [
    {
      icon: "Zap",
      title: "Easy to Set Up",
      text: "The registration process involves minimal documentation and legal formalities, making it the quickest business structure to start.",
    },
    {
      icon: "Shield",
      title: "Complete Control",
      text: "The owner has full and sole authority over all business decisions and operations without any external interference.",
    },
    {
      icon: "HandCoins",
      title: "Direct Profits",
      text: "All profits generated by the business belong exclusively to the owner and are taxed as personal income.",
    },
    {
      icon: "Files",
      title: "Minimal Compliance",
      text: "Fewer regulatory obligations and filings compared to other complex company structures like private limited companies.",
    },
  ],
  disadvantages: [
    {
      icon: "AlertTriangle",
      title: "Unlimited Liability",
      text: "The owner's personal assets are at risk to cover business debts. There is no legal distinction between personal and business assets.",
    },
    {
      icon: "Landmark",
      title: "Difficulty Raising Capital",
      text: "Cannot issue shares to raise equity and may find it challenging to secure large business loans from financial institutions.",
    },
    {
      icon: "BarChart",
      title: "Limited Lifespan",
      text: "The business's existence is tied to the owner and ceases upon the owner's death, retirement, or insolvency.",
    },
  ],
  eligibility: [
    {
      title: "General Requirements",
      items: [
        "Must be a resident citizen of India.",
        "Must be at least 18 years old.",
        "A unique business name must be chosen, which should not infringe on existing trademarks.",
      ],
    },
    {
      title: "Business Activity",
      items: [
        "The business activity must be legal and not prohibited by any law in India.",
        "Necessary local or state-level permits must be obtained for regulated industries (e.g., food, trade).",
      ],
    },
  ],
  documents: [
    {
      tabTitle: "Proprietor Documents",
      content: {
        title: "Proprietor's Identity & Address Proof",
        items: [
          "Aadhaar Card (linked with mobile number)",
          "PAN Card (Mandatory for tax purposes)",
          "Passport-size Photographs",
          "Bank Account Statement or Cancelled Cheque",
        ],
      },
    },
    {
      tabTitle: "Business Address Proof",
      content: {
        title: "Proof of Business Location",
        items: [
          "Latest Utility Bill (Electricity/Water/Gas Bill for owned or rented property)",
          "Rent Agreement (if the premises are rented)",
          "No-Objection Certificate (NOC) from the Landlord (if rented)",
        ],
      },
    },
    {
      tabTitle: "Key Registrations",
      content: {
        title: "Essential Business Registrations",
        items: [
          "GST Registration Certificate (if turnover exceeds the threshold)",
          "MSME/Udyam Registration Certificate (recommended for benefits)",
          "Shop and Establishment Act License (as per state laws)",
        ],
      },
    },
  ],
  registrationProcess: [
    {
      step: 1,
      title: "Choose a Business Name",
      description:
        "Select a unique and suitable name for your proprietorship. This can be your own name or a trade name.",
    },
    {
      step: 2,
      title: "Open a Business Bank Account",
      description:
        "Open a current bank account in the name of your proprietorship. This is a primary proof of the business's existence.",
    },
    {
      step: 3,
      title: "Obtain Basic Registrations",
      description:
        "Apply for necessary local registrations like the Shop and Establishment Act License and the central Udyam Registration for MSMEs.",
    },
    {
      step: 4,
      title: "Apply for GST Registration",
      description:
        "If your business turnover is expected to exceed the GST threshold (₹40 lakh for goods, ₹20 lakh for services), you must obtain GST registration.",
    },
  ],
  fees: [
    {
      component: "GST Registration",
      fees: "Free",
      remarks: "Government portal charges no fee for GST registration.",
    },
    {
      component: "MSME (Udyam) Registration",
      fees: "Free",
      remarks:
        "This is a free registration offered by the government to avail MSME benefits.",
    },
    {
      component: "Shop & Establishment License",
      fees: "₹1,000 – ₹5,000",
      remarks:
        "Fees are determined by respective state municipal corporations and vary by location.",
    },
    {
      component: "Professional Fees",
      fees: "₹1,500 - ₹3,000",
      remarks:
        "Covers consultation, documentation, and filing assistance for all required registrations.",
    },
  ],
  faqs: [
    {
      q: "What is unlimited liability in a proprietorship?",
      a: "Unlimited liability means the owner is personally responsible for all business debts. If the business assets are insufficient to pay its debts, creditors can claim the owner's personal property like a car, house, or savings.",
    },
    {
      q: "Is there a specific 'Proprietorship Registration Certificate'?",
      a: "No, the government does not issue a single certificate for proprietorship. Its legal existence is established through other registrations like GST, Udyam, a Shop Act license, or simply by opening a current bank account in the business's name.",
    },
    {
      q: "Can I convert my proprietorship into a private limited company later?",
      a: "Yes, as your business grows, you can convert your proprietorship into a Private Limited Company or a One Person Company to gain benefits like limited liability, easier access to funding, and a separate legal identity.",
    },
  ],
};
